server:
  port: 8080

spring:
  application:
    name: lms-backend

  # Database Configuration
  datasource:
    url: jdbc:h2:mem:lmsdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # JPA / Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# FastAPI AI Microservice URL Configuration
ai:
  service:
    base-url: http://localhost:8005/api/v1

# Security & JWT Configuration

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 Hours (in milliseconds)

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.lms.backend: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
